# Generated by Django 4.2 on 2024-07-19 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('organization_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('description', models.CharField(max_length=255)),
                ('founded', models.IntegerField()),
                ('number_of_employees', models.IntegerField()),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.country')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='industry.industrytype')),
            ],
        ),
    ]
